INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_PROTOCOLDECODER protocoldecoder)

FIND_PATH(
    PROTOCOLDECODER_INCLUDE_DIRS
    NAMES protocoldecoder/api.h
    HINTS $ENV{PROTOCOLDECODER_DIR}/include
        ${PC_PROTOCOLDECODER_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    PROTOCOLDECODER_LIBRARIES
    NAMES gnuradio-protocoldecoder
    HINTS $ENV{PROTOCOLDECODER_DIR}/lib
        ${PC_PROTOCOLDECODER_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(PROTOCOLDECODER DEFAULT_MSG PROTOCOLDECODER_LIBRARIES PROTOCOLDECODER_INCLUDE_DIRS)
MARK_AS_ADVANCED(PROTOCOLDECODER_LIBRARIES PROTOCOLDECODER_INCLUDE_DIRS)

